### ISSUE TITLE
feat: Add `up-for-grabs` query to the README table content

### ISSUE THREAD

**Issue by tungbq** [tungbq/find-github-issue#19]
Add up-for-grabs query to the README table content:
https://github.com/tungbq/find-github-issue/blob/main/README.md#open-github-issues
- Area: All
- Name: Up For Grabs
- Link: https://github.com/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3Aup-for-grabs

**Comment by maestro-00** [comment]
Let me work on this issue.

**Comment by tungbq** [comment]
Sure, thanks @Lukada-taiya
