### ISSUE TITLE
feat: Add `bug` query to the README table content

### ISSUE THREAD

**Issue by tungbq** [tungbq/find-github-issue#21]
Add hacktoberfest query to the README table content:
https://github.com/tungbq/find-github-issue/blob/main/README.md#open-github-issues

- Area: All
- Name: Hacktoberfest
- Link: https://github.com/issues?q=is%3Aopen+no%3Aassignee+label%3Abug+

**Comment by martinezedgar** [comment]
Hi @tungbq , I would like to work on this.

**Comment by tungbq** [comment]
Sure, thanks @martinezedgar. Assigned it to you
