### ISSUE TITLE
Add CI issue with no asignee to README.md

### ISSUE THREAD

**Issue by tungbq** [tungbq/find-github-issue#3]
In README.md (https://github.com/tungbq/find-github-issue/blob/main/README.md), add following link
`[CI issues](https://github.com/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3ACI)`

**Comment by keerthi-nallaginela** [comment]
Hi, Can I take this up?

**Comment by tungbq** [comment]
> Hi, Can I take this up?

Sure, please go ahead
