### ISSUE TITLE
Add docker issues to README.md

### ISSUE THREAD

**Issue by tungbq** [tungbq/find-github-issue#4]
Append following text into README.md file
`[Docker issues: Open | No assignee](https://github.com/issues?q=is%3Aopen+is%3Aissue+label%3Adocker+no%3Aassignee)`

**Comment by akj2018** [comment]
Hi, I would like to take this issue. Contributing for the first time!

**Comment by tungbq** [comment]
> Hi, I would like to take this issue. Contributing for the first time!

Thanks for picking up this. Plz go ahead
